### ISSUE TITLE
Use babel to handle async rather than require Node7

### ISSUE THREAD

**Issue by ssomnoremac** [stripe/stripe-connect-rocketrides#1]
It seems like requiring Node@>=7 is bit restrictive. Can babel be used to handle async instead as I'm assuming this is why:

```
.../stripe-connect-rocketrides/routes/pilots/pilots.js:30
router.get('/dashboard', pilotRequired, async (req, res) => {
                                        ^ unexpected token
```

**Comment by romainhuet** [comment]
Hi Cameron,

Thanks for the suggestion! Since this is a demo app, we'd like to minimize the number of external dependencies. [Node 8](https://nodejs.org/en/blog/release/v8.0.0/) was just released as the new LTS version with async/await support.

You can feel free to use Babel in your own Stripe Connect project: it should work seamlessly. I'm going to close this issue for now, but let us know if you need help making this work with Babel.

Thanks again!
