### ISSUE TITLE
Email address capture

### ISSUE THREAD

**Issue by DogandElk** [stripe/stripe-connect-rocketrides#14]
When I view the demo, I see a field for a users' email address, but I cannot find it's input code anywhere in the project. Where is that code located ?

**Comment by romain-stripe** [comment]
Hi @DogandElk! Sorry for the delay in getting back to you on this question. Are you asking about the email address collected by Connect Express?

Connect Express automatically collects the user email, in addition to some other basic information about them. However, if you happen to have already collected the email for instance during the signup process, you can pass it over to Connect as a query parameter so that the user doesn't have to input it again. This is what I do on Rocket Rides here: https://github.com/stripe/stripe-connect-rocketrides/blob/master/server/routes/pilots/stripe.js#L18-L42.

Feel free to let me know if this doesn't answer your question. Thanks!

**Comment by DogandElk** [comment]
This is javascript and can't use it in Xcode Swift .

We are building a mobile app in IOS and we need the code in swift to capture the email address so we can send a purchase confirmation and retrieve  the customer id so we can retrieve the stored credit card information from the stripe site.

Please help.
Thanks 

Tom

**Comment by DogandElk** [comment]
On the demo on your website, the animation shows an email address , see below, however, we cannot find that code or figure out why it does not display on the pYMENT PAGE AS YOURS DOES

.

**Comment by mg-stripe** [comment]
Hey there, we don't have a Swift demo yet for Stripe showing how to accept payments; I'll take a note that we should add some. In the meantime, you may want to try asking your question on a site like Stack Overflow; they may be able to provide some practical examples to help you out.

You'll want to create an endpoint on your server that calls Stripe's API for the email address of the newly created Connect account. Your app can then send an HTTP request to retrieve that email address from the server. Hope that helps!
