### ISSUE TITLE
Deployment to GCP

### ISSUE THREAD

**Issue by JBader89** [stripe/stripe-connect-rocketrides#19]
Can you run me through how I would go about deploying something like this to Google Cloud Platform? Or Netlify. Thank you for your help

**Comment by mg-stripe** [comment]
@JBader89: Sorry for the late reply. Since Rocket Rides relies on a database (in this case, MongoDB) you'll need to deploy to a cloud environment that supports a full database.

Here's how to set up Rocket Rides on GCP:
  - Create a new project on Google Cloud and note the project ID.
  - Create a MongoDB instance on Google Compute Engine. One easy option is to use the [Bitnami MongoDB instance](https://bitnami.com/stack/mongodb/cloud/google).
  - Create a username and password created for your MongoDB instance.
  - [Reserve a static IP address](https://cloud.google.com/compute/docs/ip-addresses/reserve-static-external-ip-address) for the database instance.
  - Include the connection string in your `config.js` file, using the MongoDB URI format `mongodb://<username>:<password>@<ip-address> :27017/rocketrides`, where `27017` is the configured port for MongoDB connections.
  - Include the public domain in `config.js`: `https://<project ID>.appspot.com`
  - Deploy Rocket Rides to App Engine: `gcloud app deploy --project=<project ID>`

You should now be able to view Rocket Rides at `https://<project ID>.appspot.com`.

Hopefully we'll publish a guide in the README soon. Let me know if you have any other questions!
