### ISSUE TITLE
Onboarding asks user for business information.

### ISSUE THREAD

**Issue by JamieCorkhill** [stripe/stripe-connect-rocketrides#44]
Hello.

It's clear that this demo could mimic existing apps like Lyft, Uber, DoorDash, etc. If that's the case, then the app itself acts as a medium to transfer funds from a user to another user who performed a service.

Why, then, does the onboarding ask a pilot to provide information about their business when pilots don't have a business - they're just providing a service through the app?

I'm building a service-based marketplace and I'm integrating Stripe, but I don't want to ask the users for their business information because they don't own businesses.

Is it possible to circumvent this?

Thanks.

**Comment by Andrew-Chen-Wang** [comment]
Hey @JamieCorkhill, did you figure out the marketplace system?

I think this repository is using [Stripe Express](https://stripe.com/docs/connect/express-accounts) which seems to be customizable.

I think the "seller" is an Account object, so it's possible to create some server side code to create an Account object based on a database-backed user record. Not sure if it's connected to PaymentMethod and BankAccount objects though (could be used with SetupIntent)... still working on figuring out Stripe in general...

**Comment by JamieCorkhill** [comment]
Hi @Andrew-Chen-Wang. Thanks.

I did, for the most part, figure it out. There are a few things. Firstly, Stripe are using SSR here so they've got all their business logic with regards to OAuth happening on the server-side and within the endpoints. I believe it's fine to do that on the client-side for non-SSR apps as long as you take the appropriate security measures and keep the Stripe secret hidden.

As far as this issue, in particular, I did manage to pre-populate the fields in the onboarding sequence with my own data coming from existing DB records. What I'm not sure about is how to remove those fields completely from the onboarding flow as to not give the user the ability to change it.

**Comment by Andrew-Chen-Wang** [comment]
Hi (quick response)! I'm not much of a non-SSR guy (and vehemently dislike it from my experience haha). Are you still using Stripe express?

> I did manage to pre-populate the fields in the onboarding sequence with my own data coming from existing DB records.

Are you talking about the OAuth url's query parameters? I haven't activated my Stripe account yet with a business, but, if you did, you may want to visit your Connect settings: https://dashboard.stripe.com/settings/applications Find something under Branding. See if that helps to remove the fields.

**Comment by Andrew-Chen-Wang** [comment]
@JamieCorkhill I think for your case, you should be using Stripe Elements, not Stripe Express: https://stripe.com/docs/stripe-js

It comes with `stripe.js` (and the iOS and Android sdk). Your pre-filled fields are just that: pre-filled. That's most likely because you just inputted into the OAuth url query parameters.

**Comment by JamieCorkhill** [comment]
Hi @Andrew-Chen-Wang.

I am still using Stripe Express. I did setup Branding, but it doesn't help to remove the fields. Thank you anyway, however.

I perform all of the OAuth from the client. I'm using TypeScript on the back-end with PG and I have a React + MobX app on the front-end. I have my front-end handle all of the OAuth and it generates a CSRF State token that gets stored in session storage within the tab. When Stripe redirects back to my app, I can compare the CSRF token to prevent Cross-Site Request Forgery. During this process, Stripe makes a POST Request to my server which allows me to perform the required work on the server. The Stripe URL I redirect the user to from my client contains the pre-filled fields.

I don't need Stripe Elements in this case - I'm just interested in the onboarding components for the moment.

I'd be happy to update you here later tonight or tomorrow and I can show you the full process I go through to handle all of this without SSR and to pre-fill the fields, if you want. I don't think Stripe Express is still in beta.

It looks like Stripe do have a beta open that provides more controls over pre-filled form fields, actually. See the information box here: https://stripe.com/docs/connect/express-accounts.

**Comment by Andrew-Chen-Wang** [comment]
> It looks like Stripe do have a beta open that provides more controls over pre-filled form fields, actually

Yes, that was the "beta" I was referring to (since this repository is what's demonstrating that beta feature). I believe the Stripe elements are a way to help create your own UI for Stripe, is it not? (Still new to Stripe).

I will also be looking into it tonight. Looking forward to hearing some progress! As far as I've gotten, for now, we could use a SetupIntent and clone the Customer object's PaymentMethod objects (sources and bank account) to replicate to an [External Account](https://stripe.com/docs/api/external_accounts) using a Token. That seems to be the only way you can properly make a Payout object, too (creating an external account obj). I'm hoping, like Stripe, I can take a portion of the cost, hence I needed a Custom account rather than Standard or Express.

I'm not entirely sure how the actual workflow for marketplace works. We should go to the Stripe IRC sometime during work hours to see if any Stripe devs can help.

**Comment by Andrew-Chen-Wang** [comment]
@JamieCorkhill Here is a link to my discussion in the Stripe IRC channel: https://freenode.logbot.info/stripe/20200716#c4415502

In essence, you should allow the user to set up as a sole proprietor or business. (I asked specifically about how Lyft does it, and the answer turns out that they, too, just have business type filled out by the user). Just follow the guidance and allow the OAuth to do its trick :)

**Comment by elabx** [comment]
Hi @JamieCorkhill !

Where you able to remove the Business Details part of the form? I can prefill the business type as individual but I just can't manage to skip this part where they ask for industry and a URL.
